name = "github-mcp-proxy"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WORKER_URL = "https://github-mcp-proxy.ops-e1a.workers.dev"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "20cb14eff6cf4a9cbc7d0119018f0876"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
